apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  namespace: blueenv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: magradze/workshop:bluenginx
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "50m"
        ports:
        - containerPort: 8181
