apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
  namespace: redenv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: red
  template:
    metadata:
      labels:
        app: red
    spec:
      containers:
      - name: red
        image: magradze/workshop:rednginx
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "50m"
        ports:
        - containerPort: 8282
